Repository PavelBaptist/church_accounting, pull requests merged in 2023-12, with the labels that each got.

#4 feature: add list entities
  lib/feature/domain/entities/organizations.dart
  lib/feature/domain/entities/type_operations.dart
  lib/feature/domain/entities/user_avatar.dart
  lib/feature/domain/entities/users.dart
  lib/feature/domain/entities/wallet_operations.dart
  lib/feature/domain/entities/wallets.dart
  lib/feature/presentation/pages/finance_book_screen.dart
  pubspec.yaml
Labels: enhancement

#10 add description for entities
  lib/feature/domain/entities/organizations.dart
  lib/feature/domain/entities/type_operations.dart
  lib/feature/domain/entities/user_avatar.dart
  lib/feature/domain/entities/users.dart
  lib/feature/domain/entities/wallet_operations.dart
  lib/feature/domain/entities/wallets.dart
Labels: enhancement

#11 Feature 8/disable horizontal orientation
  lib/feature/domain/entities/type_operation.dart
  lib/feature/domain/entities/wallet_operation.dart
  lib/main.dart
Labels: feature

#24 Feature 17/use cases
  lib/common/failure.dart
  lib/feature/data/models/user_model.dart
  lib/feature/domain/entities/type_operation.dart
  lib/feature/domain/entities/wallet_operation.dart
  lib/feature/domain/repositories/organization_repository.dart
  lib/feature/domain/repositories/type_wallet_operation_repository.dart
  lib/feature/domain/repositories/user_avatar_repository.dart
  lib/feature/domain/repositories/user_repository.dart
  lib/feature/domain/repositories/wallet_operation_repository.dart
  lib/feature/domain/repositories/wallet_repository.dart
  lib/feature/domain/usecases/expense_to_wallet.dart
  lib/feature/domain/usecases/get_all_organizations.dart
  lib/feature/domain/usecases/get_all_types_wallet_operations.dart
  lib/feature/domain/usecases/get_all_types_wallet_operations_by_wallet.dart
  lib/feature/domain/usecases/get_all_user_avatars.dart
  lib/feature/domain/usecases/get_all_users.dart
  lib/feature/domain/usecases/get_all_wallet_operations.dart
  lib/feature/domain/usecases/get_all_wallets.dart
  lib/feature/domain/usecases/get_wallet.dart
  lib/feature/domain/usecases/get_wallet_operations_by_wallet.dart
  lib/feature/domain/usecases/income_to_wallet.dart
  lib/feature/domain/usecases/transfer_to_wallet.dart
  pubspec.yaml
Labels: feature, actual
